apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: idp-templates
  description: All Backstage software templates for the company
spec:
  targets:
    - https://raw.githubusercontent.com/Cloud-Focus-Tech/idp-templates/refs/heads/master/templates/hello-world/template.yaml
