apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: idp-templates
  description: All Backstage software templates for the company
spec:
  type: template
  targets:
  - ./templates/azure-rg.yaml
  - ./templates/hello-world.yaml
