apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Dotnet API Template
  title: Dotnet API Template
  description: A template for creating a Dotnet API based on the provided template
spec:
  owner: guests
  type: service
  parameters:
    - title: Project Name
      required:
        - name
      properties:
        name:
          type: string
          description: Project name
  steps:
    - id: fetch
      name: Fetch template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}       