apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hello-world
  title: Hello World 2
  description: A test template 2
spec:
  owner: guests
  type: service
  parameters:
    - title: Provide info
      required:
        - name
      properties:
        name:
          type: string
          description: Project name
  steps:
    - id: fetch
      name: Fetch template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}       